作業目標:<br>
1. 熟悉索引操作
2. 分辨合併資料方法使用時機

作業重點:<br>
1. 操作索引注意有分loc、iloc
2. 合併資料方法concat、merge、join其中有參數可以調整inner或outer

題目:<br>
讀取STOCK_DAY_0050_202009.csv串聯STOCK_DAY_0050_202010.csv，並且找出open小於close的資料

In [34]:
import pandas as pd

In [5]:
#讀取STOCK_DAY_0050_202009.csv、STOCK_DAY_0050_202010.csv
stock2009 = pd.read_csv('STOCK_DAY_0050_202009.csv')
print(stock2009)
stock2010 = pd.read_csv('STOCK_DAY_0050_202010.csv')
print(stock2010)

         date    open    high     low   close
0   109/09/01  102.45  103.35  101.85  103.35
1   109/09/02  103.65  104.05  102.30  103.00
2   109/09/03  103.70  104.30  103.20  103.30
3   109/09/04  102.00  102.70  101.90  102.55
4   109/09/07  102.55  103.05  101.90  102.40
5   109/09/08  102.75  103.10  102.45  103.00
6   109/09/09  101.75  102.35  101.15  102.30
7   109/09/10  102.80  103.35  102.60  103.20
8   109/09/11  103.20  103.35  102.80  103.25
9   109/09/14  103.50  104.55  103.25  104.55
10  109/09/15  104.45  105.20  104.25  104.95
11  109/09/16  106.55  107.00  106.35  106.55
12  109/09/17  106.05  106.35  105.10  105.40
13  109/09/18  105.40  105.70  104.85  105.30
14  109/09/21  105.20  105.90  104.35  104.45
15  109/09/22  104.30  104.30  102.95  103.10
16  109/09/23  103.50  103.50  102.40  102.95
17  109/09/24  101.55  101.80  100.25  100.45
18  109/09/25  100.75  101.45  100.05  100.65
19  109/09/28  101.35  102.30  101.00  102.30
20  109/09/29  102.75  103.50  102.15  102.55
21  109/09/30  102.75  103.45  102.60  103.00
         date    open    high     low   close
0   109/10/05  103.45  104.05  103.00  103.05
1   109/10/06  104.00  104.35  103.85  104.25
2   109/10/07  104.00  105.00  103.50  104.80
3   109/10/08  105.45  106.35  105.30  106.20
4   109/10/12  106.70  107.70  106.70  107.05
5   109/10/13  107.35  107.60  106.20  107.10
6   109/10/14  107.05  107.20  106.45  106.70
7   109/10/15  106.50  106.50  105.10  105.70
8   109/10/16  105.70  106.30  105.10  105.25
9   109/10/19  105.65  106.60  105.60  106.60
10  109/10/20  106.40  106.45  106.00  106.00
11  109/10/21  106.00  106.55  105.65  105.95
12  109/10/22  105.70  106.10  105.50  106.10
13  109/10/23  106.50  106.65  105.65  106.10
14  109/10/26  106.10  106.60  105.80  106.10
15  109/10/27  105.75  105.75  105.15  105.50
16  109/10/28  105.50  105.50  104.80  105.00
17  109/10/29  104.00  104.10  103.25  103.85
18  109/10/30  103.55  103.60  102.70  103.00

In [47]:
#串聯
concatData = pd.concat([stock2009,stock2010],axis=0)
print(concatData)

#合併
mergeData = pd.merge(stock2009,stock2010,on='date',how='outer')
print(mergeData)

         date    open    high     low   close
0   109/09/01  102.45  103.35  101.85  103.35
1   109/09/02  103.65  104.05  102.30  103.00
2   109/09/03  103.70  104.30  103.20  103.30
3   109/09/04  102.00  102.70  101.90  102.55
4   109/09/07  102.55  103.05  101.90  102.40
5   109/09/08  102.75  103.10  102.45  103.00
6   109/09/09  101.75  102.35  101.15  102.30
7   109/09/10  102.80  103.35  102.60  103.20
8   109/09/11  103.20  103.35  102.80  103.25
9   109/09/14  103.50  104.55  103.25  104.55
10  109/09/15  104.45  105.20  104.25  104.95
11  109/09/16  106.55  107.00  106.35  106.55
12  109/09/17  106.05  106.35  105.10  105.40
13  109/09/18  105.40  105.70  104.85  105.30
14  109/09/21  105.20  105.90  104.35  104.45
15  109/09/22  104.30  104.30  102.95  103.10
16  109/09/23  103.50  103.50  102.40  102.95
17  109/09/24  101.55  101.80  100.25  100.45
18  109/09/25  100.75  101.45  100.05  100.65
19  109/09/28  101.35  102.30  101.00  102.30
20  109/09/29  102.75  103.50  102.15  102.55
21  109/09/30  102.75  103.45  102.60  103.00
0   109/10/05  103.45  104.05  103.00  103.05
1   109/10/06  104.00  104.35  103.85  104.25
2   109/10/07  104.00  105.00  103.50  104.80
3   109/10/08  105.45  106.35  105.30  106.20
4   109/10/12  106.70  107.70  106.70  107.05
5   109/10/13  107.35  107.60  106.20  107.10
6   109/10/14  107.05  107.20  106.45  106.70
7   109/10/15  106.50  106.50  105.10  105.70
8   109/10/16  105.70  106.30  105.10  105.25
9   109/10/19  105.65  106.60  105.60  106.60
10  109/10/20  106.40  106.45  106.00  106.00
11  109/10/21  106.00  106.55  105.65  105.95
12  109/10/22  105.70  106.10  105.50  106.10
13  109/10/23  106.50  106.65  105.65  106.10
14  109/10/26  106.10  106.60  105.80  106.10
15  109/10/27  105.75  105.75  105.15  105.50
16  109/10/28  105.50  105.50  104.80  105.00
17  109/10/29  104.00  104.10  103.25  103.85
18  109/10/30  103.55  103.60  102.70  103.00
         date  open_x  high_x   low_x  close_x  open_y  high_y   low_y  \
0   109/09/01  102.45  103.35  101.85   103.35     NaN     NaN     NaN
1   109/09/02  103.65  104.05  102.30   103.00     NaN     NaN     NaN
2   109/09/03  103.70  104.30  103.20   103.30     NaN     NaN     NaN
3   109/09/04  102.00  102.70  101.90   102.55     NaN     NaN     NaN
4   109/09/07  102.55  103.05  101.90   102.40     NaN     NaN     NaN
5   109/09/08  102.75  103.10  102.45   103.00     NaN     NaN     NaN
6   109/09/09  101.75  102.35  101.15   102.30     NaN     NaN     NaN
7   109/09/10  102.80  103.35  102.60   103.20     NaN     NaN     NaN
8   109/09/11  103.20  103.35  102.80   103.25     NaN     NaN     NaN
9   109/09/14  103.50  104.55  103.25   104.55     NaN     NaN     NaN
10  109/09/15  104.45  105.20  104.25   104.95     NaN     NaN     NaN
11  109/09/16  106.55  107.00  106.35   106.55     NaN     NaN     NaN
12  109/09/17  106.05  106.35  105.10   105.40     NaN     NaN     NaN
13  109/09/18  105.40  105.70  104.85   105.30     NaN     NaN     NaN
14  109/09/21  105.20  105.90  104.35   104.45     NaN     NaN     NaN
15  109/09/22  104.30  104.30  102.95   103.10     NaN     NaN     NaN
16  109/09/23  103.50  103.50  102.40   102.95     NaN     NaN     NaN
17  109/09/24  101.55  101.80  100.25   100.45     NaN     NaN     NaN
18  109/09/25  100.75  101.45  100.05   100.65     NaN     NaN     NaN
19  109/09/28  101.35  102.30  101.00   102.30     NaN     NaN     NaN
20  109/09/29  102.75  103.50  102.15   102.55     NaN     NaN     NaN
21  109/09/30  102.75  103.45  102.60   103.00     NaN     NaN     NaN
22  109/10/05     NaN     NaN     NaN      NaN  103.45  104.05  103.00
23  109/10/06     NaN     NaN     NaN      NaN  104.00  104.35  103.85
24  109/10/07     NaN     NaN     NaN      NaN  104.00  105.00  103.50
25  109/10/08     NaN     NaN     NaN      NaN  105.45  106.35  105.30
26  109/10/12     NaN     NaN     NaN      NaN  106.70  107.70  106.70
27  109/10/13     NaN     NaN     NaN      NaN  107.35  107.60  106.20
28  109/10/14     NaN     NaN     NaN      NaN  107.05  107.20  106.45
29  109/10/15     NaN     NaN     NaN      NaN  106.50  106.50  105.10
30  109/10/16     NaN     NaN     NaN      NaN  105.70  106.30  105.10
31  109/10/19     NaN     NaN     NaN      NaN  105.65  106.60  105.60
32  109/10/20     NaN     NaN     NaN      NaN  106.40  106.45  106.00
33  109/10/21     NaN     NaN     NaN      NaN  106.00  106.55  105.65
34  109/10/22     NaN     NaN     NaN      NaN  105.70  106.10  105.50
35  109/10/23     NaN     NaN     NaN      NaN  106.50  106.65  105.65
36  109/10/26     NaN     NaN     NaN      NaN  106.10  106.60  105.80
37  109/10/27     NaN     NaN     NaN      NaN  105.75  105.75  105.15
38  109/10/28     NaN     NaN     NaN      NaN  105.50  105.50  104.80
39  109/10/29     NaN     NaN     NaN      NaN  104.00  104.10  103.25
40  109/10/30     NaN     NaN     NaN      NaN  103.55  103.60  102.70

    close_y
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
5       NaN
6       NaN
7       NaN
8       NaN
9       NaN
10      NaN
11      NaN
12      NaN
13      NaN
14      NaN
15      NaN
16      NaN
17      NaN
18      NaN
19      NaN
20      NaN
21      NaN
22   103.05
23   104.25
24   104.80
25   106.20
26   107.05
27   107.10
28   106.70
29   105.70
30   105.25
31   106.60
32   106.00
33   105.95
34   106.10
35   106.10
36   106.10
37   105.50
38   105.00
39   103.85
40   103.00

In [29]:
#找出open小於close的資料

In [48]:
result = mergeData.loc[(mergeData.open_x < mergeData.close_x) | (mergeData.open_y < mergeData.close_y),['date','open_x','close_x','open_y','close_y']]
print(result)
print('len=',len(result))

         date  open_x  close_x  open_y  close_y
0   109/09/01  102.45   103.35     NaN      NaN
3   109/09/04  102.00   102.55     NaN      NaN
5   109/09/08  102.75   103.00     NaN      NaN
6   109/09/09  101.75   102.30     NaN      NaN
7   109/09/10  102.80   103.20     NaN      NaN
8   109/09/11  103.20   103.25     NaN      NaN
9   109/09/14  103.50   104.55     NaN      NaN
10  109/09/15  104.45   104.95     NaN      NaN
19  109/09/28  101.35   102.30     NaN      NaN
21  109/09/30  102.75   103.00     NaN      NaN
23  109/10/06     NaN      NaN  104.00   104.25
24  109/10/07     NaN      NaN  104.00   104.80
25  109/10/08     NaN      NaN  105.45   106.20
26  109/10/12     NaN      NaN  106.70   107.05
31  109/10/19     NaN      NaN  105.65   106.60
34  109/10/22     NaN      NaN  105.70   106.10
len= 16

In [53]:
resultb = concatData.loc[concatData.open<concatData.close,['date','open','close']]
print(resultb)
print('len=',len(resultb))

         date    open   close
0   109/09/01  102.45  103.35
3   109/09/04  102.00  102.55
5   109/09/08  102.75  103.00
6   109/09/09  101.75  102.30
7   109/09/10  102.80  103.20
8   109/09/11  103.20  103.25
9   109/09/14  103.50  104.55
10  109/09/15  104.45  104.95
19  109/09/28  101.35  102.30
21  109/09/30  102.75  103.00
1   109/10/06  104.00  104.25
2   109/10/07  104.00  104.80
3   109/10/08  105.45  106.20
4   109/10/12  106.70  107.05
9   109/10/19  105.65  106.60
12  109/10/22  105.70  106.10
len= 16